### ISSUE TITLE
reporte practica final

### ISSUE THREAD

**Issue by ArturoAngonJose** [SistemasTecTlaxiaco/proyecto-final-vaii#2]
[Reporte practica final.pdf](https://github.com/SistemasTecTlaxiaco/proyecto-final-vaii/files/6770816/Reporte.practica.final.pdf)

**Comment by Rmz-Rigo** [comment]
EXCELENTE PROYECTO.
CALIFICACIÓN: 80/80.

**Comment by josealfredo79** [comment]
bien hecho y revisado
